### PR TITLE
Category search

### PR DESCRIPTION
**Pull request by zedchance**
This adds the ability to search by Award category, for example:

```
localhost:8080/category/ACTOR
```

Also, I made the README a lot simpler and instead added a link to the wiki feature of GitHub. That way, we can edit the documentation for accessing the endpoints without introducing a bunch of commits and having to do PRs. I also did this so I could paste a list of the categories available there without making the README really long. Check out the wiki [here](https://github.com/zedchance/oscars/wiki), and check out the list of categories [here](https://github.com/zedchance/oscars/wiki/Endpoints#category).

If any of the categories don't look like they belong to a movie, let me know and I'll remove them from the list. (For example I removed the `HONORARY AWARD` one because it wasn't award to movies).

### CODE REVIEW

**Review by vgalbraith — APPROVED** [review]
The Wiki and How to Use pages look great.

**Comment by zedchance** [comment]
https://github.com/zedchance/oscars/commit/dc8af45ed8c3ae555c5c84c003366dbfbf53c69d checks off the last minimum deliverable needed, and 2 non-minmums.

**Comment by zedchance** [comment]
Okay I think this is ready now.

I added a `CategoryNotFoundException` that is thrown when the endpoint can't find the specified category. I changed the exception handler to catch all `RuntimeException`s and return a 404 response code since both of the exceptions we throw are "not found" exceptions.

So now these

```
localhost:8080/hello
localhost:8080/movie/joker
localhost:8080/category/actor
```

all return 200 codes, and

```
localhost:8080/unknown
localhost:8080/movie/asdf
localhost:8080/category/asdf
```

all return 404 codes.

For example:

Screen Shot 2020-11-15 at 11 05 24 AM

**Comment by vgalbraith** [comment]
All error handling appears to be working on my end
image

image

image

**Review by Mikelutsik — APPROVED** [review]

**Pull request merged**
