### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by vgalbraith**
Unit Testing is live for the Movie class. This is only a very basic test class with at least one test for each method in the Movie class, which can be expanded upon.

image

### CODE REVIEW

**Comment by VickHead** [comment]
Current coverage
image

**Comment by zedchance** [comment]
Cool! Movie is 100% covered, wanna do Award also? Then we'd meet the minimum unit tests for 2 classes.

**Comment by vgalbraith** [comment]
Figuring out coverage on line 49 in Movie class first, was going to ask which other class we should do. Award should be fairly trivial.

**Comment by zedchance** [comment]
I'm guessing do an `updateFields()` on a Movie that doesn't exist? Something where `isSuccessful()` is false?

**Comment by vgalbraith** [comment]
image

**Review by zedchance — APPROVED** [review]
image

**Pull request merged**
