### PR TITLE
OMDb_ fetch

### PR DESCRIPTION
**Pull request by vgalbraith**
Added working functionality to fetch movie data from OMDb API.

Basic flow as follows:
   ```
OMDb_Fetch f = new OMDb_Fetch("Knives Out");
System.out.println("Title: " + f.getInfo("Title", 0));
```

easy to change Title out with another field provided by the API (Year, Plot, Genre, etc.)

### CODE REVIEW

**Comment by vgalbraith** [comment]
The index portion of
`String getInfo(String accessLabel, int index)`
will be 0 in almost all cases, the exception being if we want to pull ratings since there are 3 sources supplied. See JSON response for more context.

**Review by zedchance — APPROVED** [review]
Cool!

This will be very useful. Some cool fields are returned from OMDb (including the awards field, and some others like a poster link). Looks good!

The only thing I'd suggest adding is a method that returns a full IMDb link (using the IMDb ID from the OMDb response). That can either be added in this or in a future PR.

Its annoying that stuff in the `.idea` directory keeps being changed between our machines and seems to add conflicts... I'll need to look into what exactly is pertinent and maybe I can ignore some files. (But I will say that it still works on my machine despite some changes in some of the .iml files)

**Comment by vgalbraith** [comment]
May need to move the error check inside of some of the functions, will be clearer once we have the movie objects built and are looking to fill them with the appropriate data.

**Comment by zedchance** [comment]
Working great on my end. Yeah once we get a look at how the Movie class is outlined we can make some method that fills in fields using this stuff. You can merge this when you want, or wait for another approval from a team member to make sure its working for them also.

**Review by harnoorSingh99 — APPROVED** [review]

**Pull request merged**
